### ISSUE TITLE
any thoughts about providing support for FHIR 

### ISSUE THREAD

**Issue by wanghaisheng** [catalyzeio/baas-guides#3]

**Comment by molsches** [comment]
Hi! Thanks for the feedback.

The good news is that FHIR already has some support in the Backend as a Service itself. You can store raw JSON objects (of which FHIR in JSON form is valid JSON for BaaS) in the Backend as a Service. 

![image](https://cloud.githubusercontent.com/assets/578720/7136619/40679c3e-e278-11e4-806d-3c98b97c4e52.png)

The only thing that would require a bit of manuevering to do directly would be the querying of the MRN since it's down a level in the "identifiers" node which stores data in an array. We currently don't support querying arrays in BaaS, but this is something we are currently working on.

We'll be writing more documentation up about this and some of what we're doing on the integration side with FHIR soon. Stay tuned!

**Comment by wanghaisheng** [comment]
thx for quick response ,some doc will be great
